### ISSUE TITLE
Error when trying to compile on Delphi 7

### ISSUE THREAD

**Issue by miguelagve** [maximmasiutin/FastMM4-AVX#17]
Hi, 
I've been trying to implement this library into a program developed in Delphi 7.
When I include the stock FastMM4 library, everything works fine, but if I try to use FastMM4-AVX, I get an error when trying to run it.
The Error I get is the following:
`[Error] FastMM4.pas(1532): Invalid compiler directive: 'CODEALIGN'`
`[Fatal Error] FastMM4.pas(2143): Could not compile used unit 'FastMM4Messages.pas'`
I'm not using FullDebugMode nor replaced BorlndMM DLL, and the .inc file is using the default configuration.

Thank you for the help

**Comment by ezurschmiede** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.

Ich bin bis 2. August 2021 in den Sommerferien. Die eingehenden E-Mails werden während dieser Zeit nicht bearbeitet.

Für Support schreiben Sie bitte an ***@***.***

Schöne Grüsse
Elias Zurschmiede

delight software gmbh

**Comment by maximmasiutin** [comment]
Thank you very much for letting me know. I have tried to fix it in the commit https://github.com/maximmasiutin/FastMM4-AVX/commit/f817fb20bcb050685a1fb4f949083211190eb562

Could you please try that and let me know whether it helped?

**Comment by maximmasiutin** [comment]
Can you close the issue if it is resolved?

**Comment by miguelagve** [comment]
Thank you very much for the fast response. I'm not sure when I'll be able to try it out since I currently don't have access to Delphi, but I'll get back as soon as I possibly can

**Comment by maximmasiutin** [comment]
I will close the issue. Just send me an email whenever you find out that it is not resolved, or create a new issue.
