### ISSUE TITLE
Does not build under Delphi 5

### ISSUE THREAD

**Issue by ValtsS** [maximmasiutin/FastMM4-AVX#18]
Tried latest version:

FastMM4.pas(4813) Error: Inline assembler syntax error
FastMM4.pas(4815) Error: Inline assembler syntax error
FastMM4.pas(4818) Error: Inline assembler syntax error
FastMM4.pas(4921) Error: Inline assembler syntax error
FastMM4.pas(4922) Error: Inline assembler syntax error
FastMM4.pas(4923) Error: Inline assembler syntax error
FastMM4.pas(4924) Error: Inline assembler syntax error
FastMM4.pas(4926) Error: Inline assembler syntax error
FastMM4.pas(4927) Error: Inline assembler syntax error
FastMM4.pas(5000) Error: Inline assembler syntax error
FastMM4.pas(5001) Error: Inline assembler syntax error
FastMM4.pas(5003) Error: Inline assembler syntax error
FastMM4.pas(5004) Error: Inline assembler syntax error
FastMM4.pas(5007) Error: Inline assembler syntax error
FastMM4.pas(5008) Error: Inline assembler syntax error
FastMM4.pas(5165) Error: Inline assembler syntax error
FastMM4.pas(5166) Error: Inline assembler syntax error
FastMM4.pas(5167) Error: Inline assembler syntax error
FastMM4.pas(5168) Error: Inline assembler syntax error
FastMM4.pas(5169) Error: Inline assembler syntax error
FastMM4.pas(5170) Error: Inline assembler syntax error
FastMM4.pas(5172) Error: Inline assembler syntax error
FastMM4.pas(5173) Error: Inline assembler syntax error
FastMM4.pas(5174) Error: Inline assembler syntax error
FastMM4.pas(5257) Error: Inline assembler syntax error

And many more - it does not know how to assemble SSE instructions.

**Comment by maximmasiutin** [comment]
Thank you! Could you please check a commit that I made a minute ago that supposes to fix this problem? If it does, please close this issue if you can.

**Comment by ValtsS** [comment]
Better, but not fully, some more SSE lurking around, and an issue with PByte

Borland Delphi  Version 13.0  Copyright (c) 1983,99 Inprise Corporation
FastMM4Options.inc(764)
FastMM4Options.inc(764)
FastMM4Messages.pas(159)
FastMM4.pas(6365) Error: Inline assembler syntax error
FastMM4.pas(6366) Error: Inline assembler syntax error
FastMM4.pas(6367) Error: Inline assembler syntax error
FastMM4.pas(6368) Error: Inline assembler syntax error
FastMM4.pas(6373) Error: Inline assembler syntax error
FastMM4.pas(6374) Error: Inline assembler syntax error
FastMM4.pas(7278) Error: Incompatible types: 'Byte' and 'Char'
FastMM4.pas(20043)
Project1.dpr(7) Fatal: Could not compile used unit 'FastMM4.pas'

**Comment by maximmasiutin** [comment]
Thank you! I have fixed the "Inline assembler syntax errors" I hope, but not the Byte and Char error. Could you please get a copy once again and retry, and post a new compiler output here?

**Comment by ValtsS** [comment]
Borland Delphi  Version 13.0  Copyright (c) 1983,99 Inprise Corporation
FastMM4Options.inc(764)
FastMM4Options.inc(764)
FastMM4Messages.pas(159)
FastMM4.pas(7282) Error: Incompatible types: 'Byte' and 'Char'
FastMM4.pas(20049)
Project1.dpr(7) Fatal: Could not compile used unit 'FastMM4.pas'

at line 1729:

  PByte = PAnsiChar;

at line 7282:
      LClassInfoByte1 := PByte(LClassInfoPByte + 1)^;

**Comment by maximmasiutin** [comment]
Thank you! Please let me know whether it now works. If it won't compile, please try to fix in your code and send me the correct line.

**Comment by ValtsS** [comment]
LClassInfoByte1 := {$ifdef PByteIsPAnsiChar}Byte{$endif}(PByte(LClassInfoPByte + 1)^);

more like this.

**Comment by maximmasiutin** [comment]
Thank you! I have applied your line. Is it now OK?

**Comment by ValtsS** [comment]
Yes now it builds.
