### ISSUE TITLE
Compilation issues in FPC/Lazarus

### ISSUE THREAD

**Issue by MaxTerentiev** [maximmasiutin/FastMM4-AVX#22]
Hi

I also found some compilation issues under FPC 3.2.1/Lazarus 2.0.12:

1. For win32 platform I have this compile errors:

For DEBUG build I got error: FastMM4.pas(18823,3) Error: Argument cannot be assigned to
If I change:

  {$ifdef FPC}
  Pointer(FSwitchToThread)

to

  {$ifdef FPC}
  FSwitchToThread

They compiles OK for DEBUG. But I start getting this error for RELEASE build:
FastMM4.pas(18828,6) Error: Incompatible types: got "Pointer" expected "<procedure variable type of function:LongBool;StdCall>" and I must change them back to Pointer(FSwitchToThread)

So, you should add additional defines here for DEBUG and RELEASE builds !

2. For X86_64 DEBUG build I have similar errors in previous place and also lot of range check erros (see attached screenshot).
![X64CompileErrors](https://user-images.githubusercontent.com/15716038/136614484-e1cfd0e0-4f83-42c9-862b-51b4e776bd31.jpg)

**Comment by maximmasiutin** [comment]
Thank you for reporting that! I made both DEBUG and RELEASE builds automatically checked under FPC so this error should not happen again at least under 64-bit Linux target in FPC.

**Comment by maximmasiutin** [comment]
Please confirm that this issue has been in fact fixed.

**Comment by MaxTerentiev** [comment]
Hi !

Problem 2 (For X86_64 DEBUG build) is now fixed, all compiles well

But problem 1 - Pointer(FSwitchToThread) vs FSwitchToThread in line 18851 is still here !
For debug build it must be FSwitchToThread, for release build - Pointer(FSwitchToThread)

Tested in Lazarus 2.2.4 and FPC 3.2.2 on Windows 10 x64

**Comment by maximmasiutin** [comment]
I have fixed that in the latest commit (was managed to reproduce the issue with the SwitchToThread). Can you please pull the update and confirm that it is fixed?!
