### ISSUE TITLE
Delphi2007 & {$define LogLockContention} setting & 207 Error after

### ISSUE THREAD

**Issue by HpWDev** [maximmasiutin/FastMM4-AVX#23]
As soon I use the option {$define LogLockContention}, the unit the FastMM4DataCollector.pas will be used and requires for Delphi2007 to compile some changes as the FastMM4.pas too.

Is this known ? I could provide the altered pas file & test app... tried to use the maxim@ email without success 

In addition using the simple test app, an Error 207 is shown

Hp

**Comment by HpWDev** [comment]
[AVX106Ex-207Error-1.zip](https://github.com/maximmasiutin/FastMM4-AVX/files/7570589/AVX106Ex-207Error-1.zip)

attached is the compiles PMan.exe (located on AVX106Ex\Tests\Simple\bin) with an empty form

**Comment by HpWDev** [comment]
closed by accident

**Comment by maximmasiutin** [comment]
Unfortunately, FastMM4DataCollector.pas requires too many changes to be implemented correctly on all platforms and all compilers, including earlier Delphi compilers and FPC, therefore, I have just added an error message whenever a user tries to compile under anything that is not Delphi 2007; also, it will unlikely work for 32-bit targets.
