### ISSUE TITLE
Could not compile under FPC 3.2.2 (trunk)

### ISSUE THREAD

**Issue by barlone** [maximmasiutin/FastMM4-AVX#24]
Error
FastMM4.pas(2460,14) Error: Expected another 2 array elements

![изображение](https://user-images.githubusercontent.com/5476275/150947634-303ddc15-851c-4ec7-8430-049bddaf2594.png)

**Comment by maximmasiutin** [comment]
Thank you very much! Could you please propose a fix (pull request)?

**Comment by maximmasiutin** [comment]
I tried to reproduce this bug, but could not. Can you please let me know which compile options did you use (defines)?

**Comment by maximmasiutin** [comment]
I have fixed that in the latest commit (was managed to reproduce it). Can you please pull the update and confirm that it is fixed?!
