### ISSUE TITLE
FullDebugMode on Delphi 2007

### ISSUE THREAD

**Issue by wadealer** [maximmasiutin/FastMM4-AVX#26]
When trying to use `FullDebugMode` on `Delhi 2007` I get some errors:
[DCC Error] FastMM4.pas(8731): E2003 Undeclared identifier: 'Int8'
[DCC Error] FastMM4.pas(16037): E2003 Undeclared identifier: 'LVMIndex'
Original pleriche/FastMM4 compiles fine.

**Comment by maximmasiutin** [comment]
Thank you for reporting that! I made both DEBUG and RELEASE builds automatically checked for Delphi 2007 so this error or a similar one should not happen again. Can you please check the latest commit and confirm that it was in fact fixed?

**Comment by wadealer** [comment]
Tnx! The problem is gone.

**Comment by maximmasiutin** [comment]
Thank you for letting me know promptly!
